/*
 * IFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package marttinterface;

import java.io.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;

import javax.swing.JFileChooser;

import knowledgebase.Composite;

import visitor.ElementComposite;
import visitor.ProduceMarkups;
import visitor.Serializer;
import visitor.VisitorLearnLessStructured;
import visitor.VisitorLearnSemiStructured;

/**
 *
 * @author  __USER__
 */
public class IFrame extends javax.swing.JFrame {
	//private String knowledgesource = "FoCFNA-KB";
	private String knowledgesource = null;
	//preload kb/ec for the composer
	final String knowledge = "FoCFNA-KB";
	final String modelfile = "FNA-Model";
	private Composite kb = null;
	private ElementComposite ec = null;
	/** Creates new form IFrame */
	
	public IFrame() {
	    try {
	        kb = knowledge == null ? kb :
	            (Composite) visitor.Serializer.readback(knowledge);
	        ec = (ElementComposite) Serializer.readback(modelfile);
	      }
	      catch (SecurityException se) {
	        se.printStackTrace();
	      }
	      catch (IllegalArgumentException iae) {
	        iae.printStackTrace();
	      }
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">
	private void initComponents() {
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		sjobfolder = new javax.swing.JTextField();
		ssaveto = new javax.swing.JTextField();
		stbrowse = new javax.swing.JButton();
		sjbrowse = new javax.swing.JButton();
		strainfolder = new javax.swing.JTextField();
		ssbrowse = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		ujobfolder = new javax.swing.JTextField();
		usaveto = new javax.swing.JTextField();
		ujbrowse = new javax.swing.JButton();
		usbrowse = new javax.swing.JButton();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		skip = new javax.swing.JButton();
		learn = new javax.swing.JButton();
        setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
		//setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("MARTT Interface: Learning (Optional)");
		setResizable(false);
		jPanel1.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Supervised Learning"));
		jLabel1.setText("Training Folder");

		jLabel2.setText("Job Folder");

		jLabel3.setText("Save to");

		stbrowse.setText("Browse");
		stbrowse.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				stbrowseActionPerformed(evt);
			}
		});

		sjbrowse.setText("Browse");
		sjbrowse.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				sjbrowseActionPerformed(evt);
			}
		});

		ssbrowse.setText("Browse");
		ssbrowse.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ssbrowseActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(jLabel1).add(
																jLabel2).add(
																jLabel3))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING,
																false)
														.add(
																strainfolder,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																423,
																Short.MAX_VALUE)
														.add(sjobfolder).add(
																ssaveto))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(stbrowse).add(
																sjbrowse).add(
																ssbrowse))
										.addContainerGap(28, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jLabel1)
														.add(stbrowse)
														.add(
																strainfolder,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED,
												20, Short.MAX_VALUE)
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jLabel2)
														.add(sjbrowse)
														.add(
																sjobfolder,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.add(17, 17, 17)
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jLabel3)
														.add(
																ssaveto,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(ssbrowse))
										.addContainerGap()));

		jPanel2.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Unsupervised Learning"));
		jLabel4.setText("Job Folder");

		jLabel5.setText("Save to");

		ujbrowse.setText("Browse");
		ujbrowse.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ujbrowseActionPerformed(evt);
			}
		});

		usbrowse.setText("Browse");
		usbrowse.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				usbrowseActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jPanel2Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(jLabel4).add(
																jLabel5))
										.add(32, 32, 32)
										.add(
												jPanel2Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING,
																false)
														.add(usaveto)
														.add(
																ujobfolder,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																430,
																Short.MAX_VALUE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jPanel2Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(ujbrowse).add(
																usbrowse))
										.addContainerGap(22, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel2Layout.createSequentialGroup().addContainerGap().add(
						jPanel2Layout.createParallelGroup(
								org.jdesktop.layout.GroupLayout.BASELINE).add(
								jLabel4).add(ujobfolder,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(ujbrowse)).add(21, 21, 21).add(
						jPanel2Layout.createParallelGroup(
								org.jdesktop.layout.GroupLayout.BASELINE).add(
								jLabel5).add(usaveto,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(usbrowse)).addContainerGap(
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)));

		jLabel6
				.setText("To start a learning process, fill out the form for the chosen learning technique and click \"Learn to Mark up\" ");

		jLabel7
				.setText("To go to the main interface directly, click \"Skip\".");

		skip.setText("Skip");
		skip.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				skipActionPerformed(evt);
			}
		});

		learn.setText("Learn to Mark up");
		learn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				learnActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.add(23, 23, 23)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				jLabel6)
																		.addContainerGap(
																				77,
																				Short.MAX_VALUE))
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				jLabel7)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED,
																				280,
																				Short.MAX_VALUE)
																		.add(
																				skip,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				74,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.add(
																				61,
																				61,
																				61))))
						.add(
								org.jdesktop.layout.GroupLayout.TRAILING,
								layout.createSequentialGroup().addContainerGap(
										556, Short.MAX_VALUE).add(learn).add(
										28, 28, 28))
						.add(
								layout
										.createSequentialGroup()
										.add(28, 28, 28)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.TRAILING,
																false)
														.add(
																org.jdesktop.layout.GroupLayout.LEADING,
																jPanel2,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.add(
																org.jdesktop.layout.GroupLayout.LEADING,
																jPanel1,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap(32, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jLabel6,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												25,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jLabel7).add(skip))
										.add(16, 16, 16)
										.add(
												jPanel1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(15, 15, 15)
										.add(
												jPanel2,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE).add(learn)
										.addContainerGap()));
		pack();
	}// </editor-fold>//GEN-END:initComponents

	//GEN-FIRST:event_jButton1ActionPerformed
	private void learnActionPerformed(java.awt.event.ActionEvent evt) {
		String tfolder = strainfolder.getText();
		String jfolder = null;
		String sfolder = null;
		if (tfolder.compareTo("") != 0) {//supervised
			jfolder = sjobfolder.getText();
			sfolder = ssaveto.getText();
			supervisedLearn(tfolder, jfolder, sfolder);
		} else {//unsupervised
			jfolder = ujobfolder.getText();
			sfolder = usaveto.getText();
			unsupervisedLearn(jfolder, sfolder);
		}
		learn.setEnabled(false);
	}//GEN-LAST:event_jButton1ActionPerformed

	//GEN-FIRST:event_usbrowseActionPerformed
	private void usbrowseActionPerformed(java.awt.event.ActionEvent evt) {
		String filepath = chooseFile(JFileChooser.DIRECTORIES_ONLY);
		usaveto.setText(filepath);
	}//GEN-LAST:event_usbrowseActionPerformed

	//GEN-FIRST:event_ujbrowseActionPerformed
	private void ujbrowseActionPerformed(java.awt.event.ActionEvent evt) {
		String filepath = chooseFile(JFileChooser.DIRECTORIES_ONLY);
		ujobfolder.setText(filepath);
	}//GEN-LAST:event_ujbrowseActionPerformed

	//GEN-FIRST:event_sjbrowseActionPerformed
	private void sjbrowseActionPerformed(java.awt.event.ActionEvent evt) {
		String filepath = chooseFile(JFileChooser.DIRECTORIES_ONLY);
		sjobfolder.setText(filepath);
	}//GEN-LAST:event_sjbrowseActionPerformed

	//GEN-FIRST:event_stbrowseActionPerformed
	private void stbrowseActionPerformed(java.awt.event.ActionEvent evt) {
		String filepath = chooseFile(JFileChooser.DIRECTORIES_ONLY);
		strainfolder.setText(filepath);
	}//GEN-LAST:event_stbrowseActionPerformed

	//GEN-FIRST:event_ssbrowseActionPerformed
	private void ssbrowseActionPerformed(java.awt.event.ActionEvent evt) {
		String filepath = chooseFile(JFileChooser.DIRECTORIES_ONLY);
		ssaveto.setText(filepath);
	}//GEN-LAST:event_ssbrowseActionPerformed

	//GEN-FIRST:event_skipActionPerformed
	private void skipActionPerformed(java.awt.event.ActionEvent evt) {
		// COPY add your handling code here:
		showInterfaceFrame(null); //show interface only, do not show open folder dialog
	}
	
	public void showInterfaceFrame(String folder){
		boolean packFrame = false;
		InterfaceFrame frame = new InterfaceFrame(kb, ec);
	    //Validate frames that have preset sizes
	    //Pack frames that have useful preferred size info, e.g. from their layout
	    if (packFrame) {
	      frame.pack();
	    }
	    else {
	      frame.validate();
	    }
	    //Center the window
	    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
	    Dimension frameSize = frame.getSize();
	    if (frameSize.height > screenSize.height) {
	      frameSize.height = screenSize.height;
	    }
	    if (frameSize.width > screenSize.width) {
	      frameSize.width = screenSize.width;
	    }
	    frame.setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
	    frame.setVisible(true);
	    if(folder != null){
	    	frame.setTobeOpenedFolder(folder);
	    	frame.openActionPerformed(null);
	    }
	   this.setVisible(false);
	}//GEN-LAST:event_skipActionPerformed

	private String chooseFile(int mode) {
		String filepath = null;
		JFileChooser fchooser = new JFileChooser();
		fchooser.setCurrentDirectory(new File("C:\\Documents and Settings\\hongcui\\Desktop\\WorkFeb2008\\Projects\\"));
		fchooser.setFileSelectionMode(mode);
		if (fchooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
			File fpath = fchooser.getSelectedFile();
			filepath = fpath.getAbsolutePath();
		}
		return filepath;
	}

	private void supervisedLearn(String trainfolder, String jobfolder,
		String savefolder) {
		//TODO add progress bar
		ProgressBar bar = new ProgressBar(trainfolder, jobfolder,
        		savefolder, knowledgesource, "supervised", this);
		bar.start();
/*
		System.out.println("start supervised learning at: "+System.currentTimeMillis());
		ElementComposite ec = new ElementComposite();
		int i = trainfolder.lastIndexOf('\\');
		String dir = trainfolder.substring(0, i);
		String fname = trainfolder.substring(i+1);
		String alg = "SCCP";
	    File srcdir = new File(trainfolder);
	    File[] filelist = srcdir.listFiles();
	    for (i = 0; i < filelist.length; i++) {
	      String xml = learning.Utilities.readFile(filelist[i]);
	      xml = learning.Utilities.removeTaxon(xml);
	      if (xml.trim().compareTo("") != 0) {
	        ec.addTrain(xml, filelist[i].getName());
	      }
	    }
		System.out.println("read in "+i+"training examples at: "+System.currentTimeMillis());

      ec.accept(new VisitorLearnSemiStructured(), alg);
      
		System.out.println("learned the model at: "+System.currentTimeMillis());

      
      //Produce Markups
       boolean score = false;
       Composite kb = null;
       try{
    	   kb = knowledgesource ==null ? kb :
    		   (Composite) visitor.Serializer.readback(knowledgesource);
       }catch(SecurityException se){
    	   se.printStackTrace();
       }catch(IllegalArgumentException iae){
    	   iae.printStackTrace();
       }
       String kbsc = kb ==null? "lsc": "kbsc";
      String lrp="lrp0";
      String kblrp = "kblrp0";
      ProduceMarkups pm = new ProduceMarkups(jobfolder,savefolder, ec, kb, score, false, "SCCP", kbsc, lrp, kblrp);
      pm.produce();
	  System.out.println("done at: "+System.currentTimeMillis());
*/
      //show interfaceframe
	  
      //showInterfaceFrame(savefolder);
	}

	private void unsupervisedLearn(String jobfolder, String savefolder) {
		//call perl program to do unsupervised learning
		ProgressBar bar =new ProgressBar(null, jobfolder,
        		savefolder, null, "unsupervised", this);
		bar.start();
		/*int i = jobfolder.lastIndexOf('\\');
		String workdir = jobfolder.substring(0, i)+"\\";
		String todofoldername = jobfolder.substring(i+1);
		String databasenameprefix = todofoldername;
		i = savefolder.lastIndexOf('\\');
		String savefoldername = savefolder.substring(i+1);
		databasenameprefix = databasenameprefix.replace("-", "_");
		String[] args = {"..\\..\\unsupervised\\unsupervised.pl",workdir,todofoldername,savefoldername,"seednouns.txt", "learntnouns.txt", "graphml.xml", databasenameprefix};
		try{
			Process p = Runtime.getRuntime().exec("perl", args);
			if(p.waitFor()!= 0){
				System.err.println("Unsupervised learning failed");
				
			}
			BufferedReader stdInput = new BufferedReader(new 
	                 InputStreamReader(p.getInputStream()));

	            BufferedReader stdError = new BufferedReader(new 
	                 InputStreamReader(p.getErrorStream()));

	            // read the output from the command
	            String s = "";
	            System.out.println("Here is the standard output of the command:\n");
	            while ((s = stdInput.readLine()) != null) {
	                System.out.println(s);
	            }
	            
	            // read any errors from the attempted command

	            System.out.println("Here is the standard error of the command (if any):\n");
	            while ((s = stdError.readLine()) != null) {
	                System.out.println(s);
	            }

		}catch (Exception e){
			e.printStackTrace();
		}*/
		//showInterfaceFrame(savefolder);
	}

	public javax.swing.JButton getLearnButton(){
		return learn;
	}
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new IFrame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JButton learn;
	private javax.swing.JButton sjbrowse;
	private javax.swing.JTextField sjobfolder;
	private javax.swing.JButton skip;
	private javax.swing.JTextField ssaveto;
	private javax.swing.JButton ssbrowse;
	private javax.swing.JButton stbrowse;
	private javax.swing.JTextField strainfolder;
	private javax.swing.JButton ujbrowse;
	private javax.swing.JTextField ujobfolder;
	private javax.swing.JTextField usaveto;
	private javax.swing.JButton usbrowse;
	// End of variables declaration//GEN-END:variables

}